### ISSUE TITLE
Add Relaton for ETSI: relaton-etsi

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-etsi#1]
This is the link that provides the full ETSI catalog of "published" items:

```
https://www.etsi.org/?option=com_standardssearch&view=data&format=csv&includeScope=1&page=1&search=&title=1&etsiNumber=1&content=1&version=0&onApproval=1&published=1&withdrawn=1&historical=1&isCurrent=1&superseded=1&startDate=1988-01-15&endDate=2023-10-31&harmonized=0&keyword=&TB=&stdType=&frequency=&mandate=&collection=&sort=1&x=1698720135146
```

This is a CSV file. 

<img width="1920" alt="Screenshot 2023-10-31 at 10 47 52 AM" src="https://github.com/relaton/relaton/assets/11865/2ede829c-b7af-42ac-8e4c-471b2247aacb">

Data fields we need:
* Title
* ETSI number
* Publishing date
* PubID ("ETSI EN 300 058-3 V1.2.4 (1998-06)" => Type: "EN", Major number: "300", Minor number: "058", Part: "-3", Version: "V1.2.4", Date: "1998-06")
* Version (e.g. "V1.2.4") or Edition ("ed. 1")
* Status: EN, SG, ES approval ; Published ; Withdrawn ; Historical
* Marker: Current ; Superseded
* Keywords
* Technical Committees
* Standard Type (EN "European Standard", ES "ETSI Standard", EG "ETSI Guide", TS "Technical Specification)
* Frequencies
* Mandates
* Custom Collection ("HSs cited in OJ", "HSs not yet cited in OJ", "HSs RED cited in OJ", "HSs EMC cited in OJ")

## PubID

The PubID implementation will be done at:
* https://github.com/metanorma/pubid/issues/3

## Data

[etsi-pubids.txt.zip](https://github.com/relaton/relaton/files/13211843/etsi-pubids.txt.zip)
[ETSICatalog.csv.zip](https://github.com/relaton/relaton/files/13211844/ETSICatalog.csv.zip)

**Comment by ronaldtse** [comment]
The data repo has also been created at https://github.com/relaton/relaton-data-etsi

**Comment by opoudjis** [comment]
@ronaldtse Be aware that without a grammar, Andrej cannot do anything, and currently, I'm the one writing grammars. Doing so now, but the specification given is quite vague. @andrew2net Ask me if the data you extract does not match the grammar I come up with.

**Comment by opoudjis** [comment]
Existing relaton fields that will be used:

* Title: `//bibitem/title`
* ETSI number: `//bibitem/docnumber`
* Publishing date: `//bibitem/date[@type = 'published']`
* PubID ("ETSI EN 300 058-3 V1.2.4 (1998-06)" => Type: "EN", Major number: "300", Minor number: "058", Part: "-3", Version: "V1.2.4", Date: "1998-06"): `//bibitem/docidentifier[@type = 'ETSI']`
* Version (e.g. "V1.2.4") or Edition ("ed. 1") : `//bibitem/version/draft`, `//bibitem/edition`
* Keywords: `//bibitem/keyword`
* Status: EN, SG, ES approval ; Published ; Withdrawn ; Historical: `//bibitem/status/stage`

Extension types:

* Marker: Current ; Superseded: `//bibitem/ext/marker`
* Technical Committees : `//bibitem/ext/editorialgroup` (by default, same structure as in ISO)
* Standard Type (EN "European Standard", ES "ETSI Standard", EG "ETSI Guide", TS "Technical Specification) :  `//bibitem/ext/doctype`, `//bibitem/ext/doctype@abbreviation`
* Frequencies : `//bibitem/ext/frequency` (multiple, text)
* Mandates: `//bibitem/ext/mandate` (multiple, text)
*Custom Collection ("HSs cited in OJ", "HSs not yet cited in OJ", "HSs RED cited in OJ", "HSs EMC cited in OJ")  `//bibitem/ext/custom-collection`

**Comment by andrew2net** [comment]
> Data fields we need:

@ronaldtse how about `scope`? Shouldn't we use it as an `abstract`?

**Comment by andrew2net** [comment]
> * PubID ("ETSI EN 300 058-3 V1.2.4 (1998-06)" => Type: "EN", Major number: "300", Minor number: "058", Part: "-3", Version: "V1.2.4", Date: "1998-06")

@ronaldtse what are the parts in IDs like this `ETSI GTS 11.40-DCS V3.3.0 (1995-02)`?

**Comment by andrew2net** [comment]
> * Status: EN, SG, ES approval ; Published ; Withdrawn ; Historical

@ronaldtse there abbreviations after the `ETSI` prefix are:
```
GS, GR, TR, TS, EG, ES, EN, ETR, GTS, SR, TCRTR, TBR, NET, ETS, I-ETS
```
I guess that:
`EN` => `EN approval`
`ES` => `ES approval`

What are all other abbreviations?

**Comment by ronaldtse** [comment]
> ```
> GS, GR, TR, TS, EG, ES, EN, ETR, GTS, SR, TCRTR, TBR, NET, ETS, I-ETS
> ```
> 
> I guess that: `EN` => `EN approval` `ES` => `ES approval`
> 
> What are all other abbreviations?

All of these are not Statuses, they are "document types".

GS: Group Specification
GR: Group Report
TR: Technical Report
TS: Technical Specification
EG: ETSI Guide
ES: ETSI Standard
EN: European Standard ("European Norm")
ETR: ETSI Technical Report
GTS: GSM Technical Specification
SR: Special Report
TCRTR: Technical Committee Reference Technical Report
TBR: Technical Basis for Regulation
ETS: European Telecommunication Standard
I-ETS: Interim European Telecommunication Standard

ET: **Cannot find this in the CSV file**

**Comment by ronaldtse** [comment]
> @ronaldtse what are the parts in IDs like this `ETSI GTS 11.40-DCS V3.3.0 (1995-02)`?

DCS is together with "11.40-DCS"? I'm not sure...

I think this document has no part number:
* https://www.etsi.org/deliver/etsi_gts/11/1140/03.03.00_60/gsmts_1140dv030300p.pdf

**Comment by andrew2net** [comment]
> ET: **Cannot find this in the CSV file**

@ronaldtse do you mean NET?
"ETSI NET 005 ed.2 (1995-09)" http://webapp.etsi.org/workprogram/Report_WorkItem.asp?WKI_ID=2642
"ETSI NET 004 ed.1 (1994-06)" http://webapp.etsi.org/workprogram/Report_WorkItem.asp?WKI_ID=2627
"ETSI NET 003 ed.2 (1995-09)" http://webapp.etsi.org/workprogram/Report_WorkItem.asp?WKI_ID=2656
"ETSI NET 002 ed.2 (1994-06)" http://webapp.etsi.org/workprogram/Report_WorkItem.asp?WKI_ID=2653
"ETSI NET 001 ed.2 (1994-06)" http://webapp.etsi.org/workprogram/Report_WorkItem.asp?WKI_ID=2654

**Comment by ronaldtse** [comment]
So NET is “Norme Européenne de Télécommunication”. Another document type.

**Comment by andrew2net** [comment]
> * Status: EN, SG, ES approval ; Published ; Withdrawn ; Historical

@ronaldtse I the source statuses are "Published", "Historical", "On Approval". Should we use them as is?

**Comment by opoudjis** [comment]
`DocumentType = "European Standard" | "ETSI Standard" | "ETSI Guide" | "Technical Specification" | "Group Specification" | "Group  Report" | "Technical Report" |
"European Norm"  |  "ETSI Technical Report" | "GSM Technical Specificaiton" | "Special Report" | "Technical Committee Reference Technical Report" |
"European Telecommunication Standard" | "Interim European Telecommunication Standard" | "Norme Européenne de Télécommunication"`

I've used "European Norm" and "Norme Européenne de Télécommunication" to match the abbreviations; should I make then "European Standard" and "European Telecommunication Standard" instead? Are ETS and NET the same thing?

**Comment by ronaldtse** [comment]
> I've used "European Norm" and "Norme Européenne de Télécommunication" to match the abbreviations; should I make then "European Standard" and "European Telecommunication Standard" instead? Are ETS and NET the same thing?

### European Standard

The official name of the "European standard" is defined by the [European Commission](https://single-market-economy.ec.europa.eu/single-market/european-standards_en).

The official name of the "European standard" as stated by the EC is:
> European Standards are under the responsibility of the European Standardisation Organisations ([CEN](https://www.cen.eu/Pages/default.aspx), [CENELEC](https://www.cenelec.eu/), [ETSI](http://www.etsi.org/)) and can be used to support EU legislation and policies.

And is codified in the OJEU:
https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32012R1025
<img width="870" alt="Screenshot 2023-12-01 at 2 36 12 PM" src="https://github.com/relaton/relaton-etsi/assets/11865/c61f5147-8874-48a6-b906-60619db1251d">

So it is not "European norm".

> A harmonised standard is a European standard developed by a recognised European Standards Organisation: CEN, CENELEC, or ETSI. It is created following a request from the European Commission to one of these organisations.

I can't find where the "EN" abbreviation comes from, but the CEN/CENELEC site says:
https://www.cencenelec.eu/european-standardization/european-standards/

> A European Standard (EN) is implemented by the national CEN and CENELEC Members as a national standard, and therefore is included in the standards catalogue of CEN and CENELEC's Members, the National Standardization Organizations in 34 countries.

So still it is "European Standard".

### NET vs ETS

No, they are different things.

ETSI NET:
https://www.etsi.org/deliver/etsi_net/001_099/003/02_60/net_003e02p.pdf

<img width="1123" alt="Screenshot 2023-12-01 at 2 29 16 PM" src="https://github.com/relaton/relaton-etsi/assets/11865/bbe02fed-ac39-4327-9670-1575de832c59">

ETSI ETS:

https://www.etsi.org/deliver/etsi_i_ets/300100_300199/30010201/01_60/ets_30010201e01p.pdf

<img width="1153" alt="Screenshot 2023-12-01 at 2 29 55 PM" src="https://github.com/relaton/relaton-etsi/assets/11865/bf5ef8c1-11e9-45bb-9d83-fafcae3eeaab">

Here's an official explanation of the differences between a NET and ETS from:
https://www.etsi.org/deliver/etsi_i_ets/300001_300099/300001/01_60/ets_300001e01p.pdf

It seems like a NET has a higher approval standing than an ETS, since the ETS needs extra approval to become part of a NET.


<img width="1071" alt="Screenshot 2023-12-01 at 2 41 22 PM" src="https://github.com/relaton/relaton-etsi/assets/11865/3beca672-62f5-4e6a-97b3-c0dc7ba6d918">

**Comment by andrew2net** [comment]
Released
